const STORAGE_KEY="pmos-st-augustine-restaurant-001";let data;let activePositionId=null;
const modal=document.getElementById("position-modal");const form=document.getElementById("position-form");
async function loadCampaign(){const saved=localStorage.getItem(STORAGE_KEY);data=saved?JSON.parse(saved):await (await fetch("campaign.json")).json();save();render()}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function money(value){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value)}
function committed(p){return p.status==="reserved"||p.status==="paid"}
function render(){const c=data.campaign;document.getElementById("campaign-name").textContent=c.name;document.getElementById("campaign-meta").textContent=`${c.location} • ${c.edition}`;document.getElementById("campaign-status").textContent=c.status;document.getElementById("mailboxes").textContent=c.mailboxes.toLocaleString();document.getElementById("mail-date").textContent=c.mailDate||"Not set";
const counts={total:c.positions.length,available:c.positions.filter(p=>p.status==="available").length,reserved:c.positions.filter(p=>p.status==="reserved").length,paid:c.positions.filter(p=>p.status==="paid").length,approved:c.positions.filter(p=>p.proof==="approved").length};const done=counts.reserved+counts.paid;document.getElementById("progress-fill").style.width=`${(done/counts.total)*100}%`;document.getElementById("progress-copy").textContent=`${done} / ${counts.total} committed`;document.getElementById("revenue").textContent=money(c.positions.filter(p=>p.status==="paid").reduce((s,p)=>s+p.price,0));
document.getElementById("stats").innerHTML=[["Available",counts.available],["Reserved",counts.reserved],["Paid",counts.paid],["Proof approved",counts.approved]].map(([l,v])=>`<div class="stat"><span>${l}</span><strong>${v}</strong></div>`).join("");
document.getElementById("inventory").innerHTML=["Premium Front","Standard Back","Micro Mentions"].map(g=>`<section class="inventory-group"><h2>${g}</h2><div class="position-grid">${c.positions.filter(p=>p.group===g).map(p=>`<button class="position ${p.status}" data-id="${p.id}"><span class="id">${p.id}</span><span class="status">${p.status}</span><small>${money(p.price)}</small><small>${p.category||"No category assigned"}</small><small>${p.business||"No business assigned"}</small></button>`).join("")}</div></section>`).join("");document.querySelectorAll(".position").forEach(b=>b.addEventListener("click",()=>openPosition(b.dataset.id)))}
function openPosition(id){activePositionId=id;const p=data.campaign.positions.find(x=>x.id===id);document.getElementById("modal-group").textContent=p.group;document.getElementById("modal-position").textContent=p.id;document.getElementById("modal-price").textContent=money(p.price);["status","category","business","contact","phone","email","website","artwork","proof"].forEach(n=>form.elements[n].value=p[n]||"");checkCategory();modal.hidden=false}
function checkCategory(){const value=form.elements.category.value.trim().toLowerCase();const warning=document.getElementById("category-warning");if(!value){warning.hidden=true;return}const duplicate=data.campaign.positions.find(p=>p.id!==activePositionId&&committed(p)&&p.category.trim().toLowerCase()===value);warning.hidden=!duplicate;if(duplicate)warning.textContent=`${duplicate.category} is already assigned to ${duplicate.id}.`}
form.elements.category.addEventListener("input",checkCategory);
form.addEventListener("submit",e=>{e.preventDefault();if(!document.getElementById("category-warning").hidden&&form.elements.status.value!=="available"){alert("That category is already reserved or paid.");return}const p=data.campaign.positions.find(x=>x.id===activePositionId);["status","category","business","contact","phone","email","website","artwork","proof"].forEach(n=>p[n]=form.elements[n].value.trim());save();modal.hidden=true;render()});
document.getElementById("clear-position").addEventListener("click",()=>{const p=data.campaign.positions.find(x=>x.id===activePositionId);Object.assign(p,{status:"available",category:"",business:"",contact:"",phone:"",email:"",website:"",artwork:"pending",proof:"pending"});save();modal.hidden=true;render()});
document.getElementById("close-modal").addEventListener("click",()=>modal.hidden=true);modal.addEventListener("click",e=>{if(e.target===modal)modal.hidden=true});
document.getElementById("reset-data").addEventListener("click",()=>{if(confirm("Reset all saved campaign changes on this device?")){localStorage.removeItem(STORAGE_KEY);location.reload()}});
loadCampaign().catch(error=>{document.body.innerHTML=`<p style="padding:30px">Could not load campaign.json: ${error.message}</p>`});
